- pull_request_template.md
- src/main/java/com/example/eight/artwork/controller/ArtworkController.java
- src/main/java/com/example/eight/artwork/entity/Element.java
- src/main/java/com/example/eight/artwork/entity/Part.java
- src/main/java/com/example/eight/artwork/entity/Relic.java
- src/main/java/com/example/eight/artwork/entity/SolvedElement.java
- src/main/java/com/example/eight/artwork/entity/SolvedPart.java
- src/main/java/com/example/eight/artwork/entity/SolvedRelic.java
- src/main/java/com/example/eight/artwork/repository/RelicRepository.java
- src/main/java/com/example/eight/artwork/service/ArtworkService.java
#1 
- 작품 mvc 패턴을 생성했습니다.
- 작품 관련 엔티티들을 생성하고 관계를 추가했습니다.
ex) artwork/yeni -> main
-
> [FEAT] 작품 MVC 패턴 및 작품 엔티티 생성

- build.gradle
- src/main/java/com/example/eight/user/entity/Role.java
- src/main/java/com/example/eight/user/entity/User.java
- src/main/java/com/example/eight/user/repository/UserRepository.java
- src/main/java/com/example/eight/user/service/UserService.java
- src/main/resources/application-oauth.properties
- src/main/resources/application.properties
- src/test/java/com/example/eight/user/UserTest.java
#1 
- 유저 엔티티와 리포지토리를 생성했습니다.
- 구글 Oauth 초기 설정을 진행했습니다.
login/jina -> main
-
> [FEAT] 유저 엔티티 생성 및 구글 Oauth 초기 설정

- src/main/java/com/example/eight/artwork/controller/ArtworkController.java
- src/main/java/com/example/eight/artwork/dto/PartsResponseDto.java
- src/main/java/com/example/eight/artwork/service/ArtworkService.java
#8 
- API 시트에 맞게 URI 변경했습니다.
ex) artwork/yeni -> main
- API 시트는 노션 참고해주세요!
> [UPDATE] 작품 부분 정보 조회 API 응답에 뱃지 추가

- .github/workflows/ci.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/resources/application.properties
- src/test/java/com/example/eight/global/jwt/JwtServiceTest.java
- src/test/java/com/example/eight/user/UserTest.java
#22 
- GitHub Action으로 CI를 구축했습니다.
ex) ci-githubaction/yeni -> main
> [CHORE] GitHub Action CI 구축

- .github/workflows/ci.yml
#26 
- GitHub Action을 통해 빌드 성공 시 빌드 압축 파일 생성을 하도록 했습니다.
- 이후 빌드 압축 파일은 S3 버킷에 업로드 됩니다.
ex) ci-githubaction/yeni -> main
- aws 관련 정보들은 노션 문서에 있습니다!
> [CHORE] GitHub Action과 S3 연동

- src/main/java/com/example/eight/artwork/entity/SolvedElement.java
- src/main/java/com/example/eight/artwork/entity/SolvedPart.java
- src/main/java/com/example/eight/artwork/entity/SolvedRelic.java
- src/main/java/com/example/eight/artwork/repository/SolvedElementRepository.java
- src/main/java/com/example/eight/artwork/repository/SolvedPartRepository.java
- src/main/java/com/example/eight/artwork/repository/SolvedRelicRepository.java
- src/main/java/com/example/eight/artwork/service/ArtworkService.java
#5
- 요소 인식시 로그인한 유저정보를 추가했습니다.
- Element를 모두 인식한 경우 Part수집기록에도 데이터를 추가하고, Part를 모두 인식한 경우 Relic 수집기록에도 데이터를 추가합니다. 
- 이미 수집한 기록이 있다면 solvedAt만 업데이트 합니다. 
artwork/jina -> main
- API 테스트 완료했습니다. 노션 API 시트 참고해주세요.
> [UPDATE] 작품 요소인식 API 업데이트

- src/main/java/com/example/eight/global/config/SecurityConfig.java
> CORS 설정 추가

- src/main/java/com/example/eight/global/config/SecurityConfig.java
> ✨ [UPDATE] CORS 헤더 설정 추가

- src/main/java/com/example/eight/global/config/SecurityConfig.java
#33 
- 
artwork/jina -> main
-
> [Chore] CORS 설정 변경 #33

- src/main/java/com/example/eight/global/jwt/service/JwtService.java
> [FIX] refreshToken 저장 오류 수정 

- src/main/java/com/example/eight/global/jwt/service/JwtService.java
- src/main/java/com/example/eight/global/oauth2/controller/OauthController.java
> [FIX] 서버 로그 추가

- src/main/java/com/example/eight/artwork/service/ArtworkService.java
> [UPDATE] 작품 이미지 DB에서 불러오도록 변경

- build.gradle
> [UPDATE] Validation dependency 추가

- src/main/java/com/example/eight/global/oauth2/service/OauthService.java
> [UPDATE] 리다이렉트 주소 프론트 서버로 변경 

- src/main/java/com/example/eight/artwork/controller/ArtworkController.java
- src/main/java/com/example/eight/artwork/dto/RelicInfoDto.java
- src/main/java/com/example/eight/artwork/dto/RelicResponseDto.java
- src/main/java/com/example/eight/artwork/service/ArtworkService.java
#50 
- 전체 작품에 대해 조회를 할 수 있는 API입니다.
ex) artwork/yeni-> main
> [feature] 전체 작품 조회 API

- src/main/resources/application-oauth.properties
#57 
- API 서비스 키 변경 및 CI/CD 환경변수에 수정을 하는 작업입니다.
ex) artwork/yeni -> main
> [FIX] API Service Key 변경

- src/main/java/com/example/eight/artwork/controller/ArtworkController.java
- src/main/java/com/example/eight/artwork/dto/RelicDetailResponseDto.java
- src/main/java/com/example/eight/artwork/repository/PartRepository.java
- src/main/java/com/example/eight/artwork/service/ArtworkService.java
#59 
-  dto 생성
- controller & service 로직 작성
- api 테스트
artwork/yeni -> main
> [FEAT] 작품의 전체 해설 조회 API 

- src/main/java/com/example/eight/collection/controller/CollectionController.java
- src/main/java/com/example/eight/collection/dto/CollectionDto.java
- src/main/java/com/example/eight/collection/dto/CollectionResponseDto.java
- src/main/java/com/example/eight/collection/service/CollectionService.java
#63 
- 유저별 도감을 조회하는 API입니다.
collection/jina -> main
- 노션 API 시트 참고해주세요!
> [FEAT] 도감 조회 API 추가

- build.gradle
- src/main/java/com/example/eight/artwork/entity/Element.java
- src/main/java/com/example/eight/artwork/entity/Part.java
- src/main/java/com/example/eight/gpt/controller/GptController.java
- src/main/java/com/example/eight/gpt/dto/GptRequestDto.java
- src/main/java/com/example/eight/gpt/dto/GptResponseDto.java
- src/main/java/com/example/eight/gpt/service/ChatService.java
- src/main/resources/application-oauth.properties
#66 
-  service key 발급 후, GPT API 연동한 base API를 개발하였습니다.
gpt/yeni -> main
> [FEAT] ChatGPT 연동 및 서비스 구현

- src/main/java/com/example/eight/gpt/controller/GptController.java
- src/main/java/com/example/eight/gpt/service/ChatService.java
- src/main/resources/application-oauth.properties
#66 
요소 해설 제공 API에 사용되는 GPT의 응답 개선 작업입니다.
- 프롬포트 수정
- 토큰 조정
- 에러 트러블슈팅
gpt/yeni -> main
> [UPDATE] GPT 응답 개선 작업

- src/main/java/com/example/eight/artwork/repository/ElementRepository.java
- src/main/java/com/example/eight/gpt/controller/GptController.java
- src/main/java/com/example/eight/gpt/dto/GptRequestDto.java
- src/main/java/com/example/eight/gpt/dto/GptResponseDto.java
- src/main/java/com/example/eight/gpt/service/ChatService.java
- src/main/resources/application-oauth.properties
#71 
**GPT를 통한 요소 해설 제공 API의 response를 클라이언트 요청에 맞게 업데이트하는 작업입니다.**
- dto 수정
- controller, service 로직 업데이트
- gpt 모델 업그레이드 
gpt/yeni -> main
> [update] GPT를 통한 요소 해설 제공 API response 업데이트

- src/main/java/com/example/eight/gpt/service/ChatService.java
#72 
- 요소 이미지를 응답 객체에 포함하도록 변경했습니다. 
gpt/yeni -> main
> [UPDATE] GPT를 통한 요소 해설 제공 API 이미지 response 추가
